name: GitHub-Profile-Summary-Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: vitoriamaria-bp
          BRANCH_NAME: "main"
          UTC_OFFSET: -3
          AUTO_PUSH: true
          THEME: "github_dark"
